FROM python:3.11

# SET THE WORKING DIRECTORY
WORKDIR /app

# COPY REQUERiMENTS.TXT TO THE WORKING DIRECTORY
COPY requirements.txt .

# INSTALL THE REQUERIMENTS
RUN pip install -r requirements.txt

# COPY THE CURRENT DIRECTORY CONTENTS INTO THE CONTAINER  AT /APP
#COPY . .

EXPOSE 8000
# RUN APP.PY WHEN THE CONTAINER LAUNCHES
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]



