# Generated by Django 5.0.6 on 2024-06-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='display_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
